language: python

branches:
  except:
    - gh-pages

python:
  - "2.7"

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy

install:
  - pip install tox --use-mirrors
  - pip install coveralls

script: tox

after_success:
  coveralls